server:
  port: 19888
#mybatis??
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
swagger:
  version: 1.0.0
  title: wordDemo
  description: demo?? API
#http://localhost:19888/swagger-ui.html
#logging??
logging:
  level:
    root: info
    com.kdgc.worddemo.mapper: debug
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/word_demo?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
